enableGlobalCache: true

logFilters:
  - code: YN0013
    level: discard

# We probably do not need yarn reproducibility. Re-add if we do.
# yarnPath: .yarn/releases/yarn-berry.cjs

nodeLinker: node-modules
